export const roxyPhrases = {
  homeMorning: [
    'Buenos días. Podemos empezar con calma.',
    'Me alegra verte esta mañana.',
    'No hay prisa. Mira primero lo más simple.',
    'El día apenas comienza. Una cosa a la vez.',
    'Estoy aquí. Podemos ver qué sigue.',
    'Empieza por algo pequeño y claro.',
    'Aún hay silencio suficiente para pensar.',
    'Respira un momento. Después seguimos.',
    'Hoy no hace falta hacerlo perfecto.',
    'Que la mañana sea amable contigo.',
  ],
  homeAfternoon: [
    'Buenas tardes. Podemos empezar por una sola cosa.',
    'Aún queda día. No lo llenes de golpe.',
    'Miremos qué sigue, sin apurarnos.',
    'Si algo quedó pendiente, lo veremos con calma.',
    'Me alegra encontrarte aquí.',
    'Una tarde también puede ordenarse despacio.',
    'No necesitas resolverlo todo ahora.',
    'Elige una cosa. Yo te acompaño.',
    'Si el día pesa un poco, avancemos más lento.',
    'Vamos paso a paso.',
  ],
  homeNight: [
    'Buenas noches. Descansa un momento.',
    'Si fue un día largo, baja el ritmo.',
    'No todo debe cerrarse esta noche.',
    'Podemos dejar una sola cosa ordenada.',
    'Estoy aquí. No hay prisa.',
    'La noche también sirve para recuperar fuerzas.',
    'Si algo salió mal, mañana lo intentamos de nuevo.',
    'Hazlo pequeño, si aún queda algo por hacer.',
    'No fuerces más de lo necesario.',
    'Quédate un momento. Después decides.',
  ],
  homeReturnAfterDays: [
    'Me alegra verte otra vez.',
    'No voy a reprocharte la ausencia. Sigamos desde aquí.',
    'Volver también cuenta.',
    'Han pasado algunos días. Empecemos despacio.',
    'No hace falta explicar todo ahora.',
    'Miremos lo que quedó esperando.',
    'Si te perdiste un poco, podemos retomar con calma.',
    'Estoy aquí. Empezamos de nuevo.',
    'Una pausa no borra lo que ya intentaste.',
    'Primero una cosa. Después veremos lo demás.',
  ],
  alarmEarly: [
    'Es temprano, lo sé. Pero conviene levantarse ahora.',
    'Todavía cuesta abrir los ojos. Empieza despacio.',
    'Si esto estaba marcado, era por una razón.',
    'Levántate con calma. No necesitas correr.',
    'Un primer paso basta para salir de la cama.',
    'Vamos. El día puede esperar unos segundos más, pero no mucho.',
    'No pienses en todo. Solo levántate.',
    'Abrígate si hace frío. Después seguimos.',
    'Esto será más fácil si empiezas ahora.',
    'Estoy contigo. Arriba, poco a poco.',
  ],
  study: [
    'Estudia un bloque corto. Entender bien una parte ya cuenta.',
    'No intentes aprender todo de una vez.',
    'Una buena lección necesita paciencia.',
    'Primero lo básico. Después lo difícil.',
    'Si te pierdes, vuelve al primer paso.',
    'Aprender magia también empieza con ejercicios simples.',
    'Repite con calma. No es una derrota.',
    'Anota lo que no entiendas. Eso también es estudiar.',
    'Hoy basta con avanzar un poco.',
    'No busques perfección. Busca entender.',
  ],
  work: [
    'Mira primero lo que vence antes.',
    'No hace falta cargar con todo al mismo tiempo.',
    'Una tarea clara es mejor que diez abiertas.',
    'Resuelve lo urgente sin perder la calma.',
    'Si algo puede esperar, déjalo esperar.',
    'Empieza por lo que tenga menos ruido.',
    'Cuida tu atención. También se gasta.',
    'Trabaja con orden, no con prisa.',
    'Cierra una cosa antes de abrir otra.',
    'Lo importante merece un poco de silencio.',
  ],
  health: [
    'Esto es de salud. Mejor verlo con tiempo.',
    'Lleva lo que necesites y sal sin apuro.',
    'No minimices lo que tu cuerpo intenta decir.',
    'Cuidarte también es una tarea importante.',
    'Si tienes dudas, pregúntalas con calma.',
    'Anota lo importante antes de ir.',
    'No lo dejes demasiado lejos.',
    'La salud no necesita valentía, necesita atención.',
    'Ve con tiempo. Eso evita errores pequeños.',
    'Hazlo por cuidado, no por miedo.',
  ],
  gym: [
    'No hace falta entrenar perfecto. Ir ya cuenta.',
    'Muévete un poco. Eso puede ser suficiente.',
    'Empieza suave y escucha al cuerpo.',
    'No lo conviertas en castigo.',
    'Un entrenamiento simple también sirve.',
    'Si estás cansado, baja la intensidad.',
    'La constancia suele ser más amable que la fuerza.',
    'Haz lo posible hoy. Mañana veremos.',
    'No compitas con una versión imaginaria de ti.',
    'Moverse un poco también despeja la mente.',
  ],
  calmDay: [
    'Ese día parece tranquilo.',
    'Puede servir para descansar un poco.',
    'No todo debe estar lleno.',
    'Un día suave también tiene valor.',
    'Quizá puedas adelantar algo pequeño.',
    'Si no hay urgencias, no inventes una.',
    'Aprovecha el silencio con cuidado, no con prisa.',
    'Hoy puede quedar simple.',
    'Respirar un poco no es perder el tiempo.',
    'Dejemos espacio para pensar.',
  ],
  busyWeek: [
    'Esta semana tiene varias cosas.',
    'No agregaría demasiado más si puedes evitarlo.',
    'Conviene mirar primero lo más cercano.',
    'Una semana cargada se ordena por partes.',
    'No intentes sostenerlo todo en la cabeza.',
    'Elige bien dónde poner tu energía.',
    'Si algo no es necesario, déjalo para después.',
    'Vamos a cuidar el ritmo.',
    'Una cosa por vez. Incluso esta semana.',
    'Será más fácil si no lo haces todo hoy.',
  ],
  taskCompleted: [
    'Bien hecho. Lo terminaste.',
    'No tenía que salir perfecto.',
    'Eso ya quedó atrás. Buen trabajo.',
    'Avanzaste. Aunque haya sido poco, cuenta.',
    'Me alegra que lo hayas completado.',
    'Una cosa menos esperando.',
    'Puedes descansar un momento.',
    'Buen paso. Sigamos cuando estés listo.',
    'Eso requirió atención. Se nota.',
    'Terminaste algo. No lo pases por alto.',
  ],
  taskMissed: [
    'No salió hoy. Está bien.',
    'Mañana lo intentamos de nuevo, pero más pequeño.',
    'Fallar una tarea no borra el camino.',
    'No te castigues por esto.',
    'Miremos qué lo hizo difícil.',
    'Puede esperar un poco, si lo retomamos con cuidado.',
    'Hoy no alcanzó. A veces pasa.',
    'Vuelve al primer paso cuando puedas.',
    'No lo conviertas en una culpa.',
    'Sigamos desde aquí.',
  ],
};

export function getRandomRoxyPhrase(
  group: keyof typeof roxyPhrases
): string {
  const phrases = roxyPhrases[group];
  const index = Math.floor(Math.random() * phrases.length);

  return phrases[index];
}
